<%@ Page Title="" Language="C#" MasterPageFile="~/PartyProduct.Master" AutoEventWireup="true" CodeBehind="AssignPartyList.aspx.cs" Inherits="PartyProductWebForm.AssignParty.AssignPartyList" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        #<% =secTitle.ClientID %> {
            font-size: 40px;
            display: flex;
            justify-content: center;
        }

        #<% =GridView1.ClientID %> {
            display: flex;
            justify-content: center;
            padding: 10px;
            font-size: 20px;
            border: none;
        }

        #<% =Button1.ClientID %> {
            margin-left: auto;
        }

        #<% =GridView1.ClientID %> tr, #<% =GridView1.ClientID %> tr th {
            padding: 10px;
            text-align: center;
        }

            #<% =GridView1.ClientID %> tr:nth-child(odd) {
                background-color: beige;
            }

        .main-container {
            width: 40%;
            display: flex;
            justify-content: center;
            flex-direction: column;
            align-items: center;
        }

        .table-head {
            text-align: center;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="main-container">
        <asp:Label ID="secTitle" runat="server" Text="Assign Party List"></asp:Label>
        <asp:Button ID="Button1" runat="server" Text="Add New Party" OnClick="Button1_Click" />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false">
            <Columns>
                <asp:BoundField DataField="ID" ReadOnly="true" HeaderText="ID" ControlStyle-CssClass="table-head">
                    <ControlStyle CssClass="table-head"></ControlStyle>
                </asp:BoundField>
                <asp:BoundField DataField="Party_Name" ReadOnly="true" HeaderText="Party Name" />
                <asp:BoundField DataField="Product_Name" ReadOnly="true" HeaderText="Product Name" />
                <asp:TemplateField HeaderText="Actions">
                    <ItemTemplate>
                        <asp:Button ID="edtBtn" runat="server" Text="Edit" OnCommand="edtBtn_Command" CommandName="EditAssignParty"
                            CommandArgument='<%#DataBinder.Eval( Container,"DataItemIndex") %>' />
                        <asp:Button ID="delBtn" runat="server" Text="Delete" OnCommand="delBtn_Command" CommandName="DeleteAssignParty"
                            CommandArgument='<%#DataBinder.Eval( Container,"DataItemIndex") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </div>
</asp:Content>
